Adding featurization_attendance IPython notebook
OpenEducationAnalytics/OpenEducationAnalytics pull request #205
Opened 2023-01-20 17:06 UTC by abhaysibal

Adding featurization_attendance IPython notebook

2023-01-20 17:14 UTC, changliu2 commented
approved

2023-01-24 17:06 UTC, genegc requested changes

2023-01-24 17:06 UTC, genegc commented on packages/package_catalog/Predicting_Student_Well_Being/pipelines/Featurization_Attendance.json
> +				"id": "/subscriptions/3ad04f94-581c-468f-b2e4-966452b69cec/resourceGroups/tasedu-oea-aso-prod-rg/providers/Microsoft.Synapse/workspaces/tasedu-oea-aso-prod-syn/bigDataPools/generalv3",
there shouldn't be a reference to a specific subscription

2023-01-24 17:06 UTC, genegc commented on packages/package_catalog/Predicting_Student_Well_Being/pipelines/Featurization_Attendance.json
> +				"id": "/subscriptions/3ad04f94-581c-468f-b2e4-966452b69cec/resourceGroups/tasedu-oea-aso-prod-rg/providers/Microsoft.Synapse/workspaces/tasedu-oea-aso-prod-syn/bigDataPools/generalv3",
please remove subscription specific details by using linked services

2023-02-16 16:05 UTC, genegc approved these changes

2023-02-16 16:05 UTC, merged