Dev edfi changes/v0.1
OpenEducationAnalytics/OpenEducationAnalytics pull request #323
Opened 2023-09-22 14:20 UTC by virajjayant-neenopal

Hi Team,

This branch has relevant commits to improve the Ed-Fi Module.

Please note that OEA base functions like upsert, overwrite, append, add_to_lake_db have also been modified to enable the implementation of the above changes. 

For more details,
1. Kindly refer to the README.md file in */Ed-Fi/utils/ 
2. For EdFi_Refine notebook - kindly read the comments and acknowledgements added at the top of the notebook

Warm Regards,
Viraj Jayant
(Representing Edwire)

2023-09-29 14:00 UTC, cviddenKwantum requested changes
See code comments and please revise.

2023-09-29 14:00 UTC, cviddenKwantum commented on framework/synapse/notebook/OEA_py.ipynb
> +        "                logger.info('Partitioning columns absent - defaulting to DistrictId and SchoolYear as partitioning columns')\n",
This looks like EdFi specific code and should belong in the edfi_py.ipynb module class. Please remove all such code from the OEA_py.ipynb notebook class.

2023-10-27 14:12 UTC, virajjayant-neenopal commented
https://docs.google.com/document/d/1n-If5ScrDTPVZpjmgN3Bq0A2uEzq7o5zssaoM-H1gZE/edit?usp=sharing

2023-11-02 13:35 UTC, cviddenKwantum approved these changes

2023-11-02 13:36 UTC, cviddenKwantum approved these changes

2023-11-10 14:08 UTC, cviddenKwantum approved these changes

2023-11-10 14:20 UTC, v-chadvidden approved these changes

2023-11-10 14:21 UTC, v-chadvidden approved these changes

2023-11-10 14:35 UTC, genegc approved these changes

2023-11-10 14:37 UTC, merged